server {
    listen 80;
    server_name localhost;

    root /var/www/html/backend/public;
    index index.php;

    # Accueil
    location = / {
        try_files /frontend/index.html =404;
    }

    # Assets
    location ^~ /assets/ {
        alias /var/www/html/backend/public/frontend/assets/;
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    # Partials
    location ^~ /partials/ {
        alias /var/www/html/backend/public/frontend/partials/;
        try_files $uri =404;
    }

    # Favicon
    location = /favicon.ico {
        try_files /frontend/favicon.ico =404;
        access_log off;
        log_not_found off;
    }

    # Pages frontend propres : /login -> frontend/login.html
    location / {
        try_files $uri $uri/ /frontend$uri.html /index.php?$query_string;
    }

    # PHP
    location ~ ^/index\.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    # Bloquer les autres .php
    location ~ \.php$ {
        return 404;
    }
}