server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    # Accueil
    location = / {
        try_files /frontend/index.html =404;
    }
    # servir le front statique
    location ^~ /frontend/ { try_files $uri =404; }
    location ^~ /assets/   { try_files $uri =404; access_log off; expires 7d; }
    location ^~ /partials/ { try_files $uri =404; }

    # API PHP
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Assets
    location ^~ /assets/ {
        alias /var/www/html/public/frontend/assets/;
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    # Partials
    location ^~ /partials/ {
        alias /var/www/html/public/frontend/partials/;
        try_files $uri =404;
    }

    # API : /api/login -> backend /login
    location ^~ /api/ {
        rewrite ^/api(/.*)$ $1 break;

        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param REQUEST_URI $uri;
        fastcgi_param PATH_INFO $uri;
    }

    # Pages frontend propres
    location / {
        try_files $uri $uri/ /frontend$uri.html /index.php?$query_string;
    }

    # PHP front controller
    location ~ ^/index\.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }

    # Sécurité
    location ~ \.php$ {
        return 404;
    }
}